# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='password',
        ),
    ]
